name: AdminPanel
version: 2.0
main: com.JavaBeast.AdminPanel.Main
author: JavaBeast
website: javabeast.bplaced.net
database: false
description: gui for admins to manage your minecraft server

commands:
  admin:
    description: opens the admin panel gui or if info is added to the arguments a info will be displayed in the chat.
    permission: adminpanel.command.admin
    aliases:
      - ap
      - panel
    permission-message: sorry but you don't have the permission to do that.
    usage: /admin [info]