name: AdminPanel
version: 0.0.1
main: com.beastdevelopment.adminpanel.javabeast.Main
api-version: 1.8
website: http://<ip>:<port>/?usr=<usr>&pw=<pw>
author: JavaBeast
database: false
description: online web panel to control the server
